name: My Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch data from sunsetbot
        run: curl -s 'https://sunsetbot.top/?query_id=1212123&intend=select_city&query_city=%E5%8C%97%E4%BA%AC&event_date=None&event=set_1&times=None' -o result.json

      - name: Parse json
        id: parse
        run: | 
          python3 -c "import json; print(json.load(open('result.json'))['local_quality'])" | tee quality.txt
          echo "QUALITY=$(cat quality.txt)" >> $GITHUB_ENV
          python3 -c "import json; print(json.load(open('result.json'))['table_content'])" | tee table_content.txt
          echo "TABLE_CONTENT=$(cat table_content.txt)" >> $GITHUB_ENV

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: result-json
          path: result.json

      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Sunsetbot 日落预报 - ${{ env.QUALITY }}'
          body: 'The quality of sunset today in Beijing is ${{ env.QUALITY }} \n ${{ env.TABLE_CONTENT }}.'
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_USERNAME }}