name: My Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to the world
        run: echo "Hello, world!"