name: My Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch data from sunsetbot
        run: |
          curl -s 'https://sunsetbot.top/?query_id=1212123&intend=select_city&query_city=%E5%8C%97%E4%BA%AC&event_date=None&event=set_1&times=None' -o result.json
          curl -s 'https://sunsetbot.top/?query_id=1212123&intend=select_city&query_city=%E5%8C%97%E4%BA%AC&event_date=None&event=set_2&times=None' -o result2.json

      - name: Parse json
        id: parse
        run: | 
          python3 -c "import json; print(json.load(open('result.json'))['tb_quality'].replace('<br>', ' '))" | tee quality1.txt
          echo "QUALITY1=$(cat quality1.txt)" >> $GITHUB_ENV
          python3 -c "import json; print(json.load(open('result.json'))['tb_event_time'].replace('<br>', ' '))" | tee time1.txt
          echo "TIME1=$(cat time1.txt)" >> $GITHUB_ENV
          python3 -c "import json; print(json.load(open('result2.json'))['tb_quality'])" | tee quality2.txt
          echo "QUALITY2=$(cat quality2.txt)" >> $GITHUB_ENV

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: result-json
          path: result.json

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Sunsetbot 日落预报 - ${{ env.QUALITY1 }}'
          body: |
            北京今日的日落质量为 ${{ env.QUALITY1 }}，日落将于 ${{ env.TIME1 }}发生。

            明日质量为 ${{ env.QUALITY2 }}。

            请查看 https://sunsetbot.top 获取更多信息。

            —————————————————

            The quality of sunset today in Beijing is ${{ env.QUALITY1 }}. This will happen in ${{ env.TIME1 }}.

            The quality tomorrow is ${{ env.QUALITY2 }}. 

            Check https://sunsetbot.top for more information.
          attachments: result.json,result2.json
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_USERNAME }}